# Generated by Django 3.0.3 on 2020-09-27 12:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideosList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(max_length=255)),
                ('list_cover', models.ImageField(blank=True, upload_to='list cover')),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('discription', models.TextField(blank=True, verbose_name='List discription')),
            ],
        ),
        migrations.CreateModel(
            name='VideosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=250)),
                ('video_url', models.URLField(max_length=1200)),
                ('video_discription', models.TextField()),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('videos_lists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.VideosList')),
            ],
        ),
    ]
