# Generated by Django 3.0.3 on 2020-10-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200929_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_user',
            field=models.EmailField(max_length=254),
        ),
    ]
