# Generated by Django 3.0.3 on 2020-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201001_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='to_user',
            field=models.EmailField(max_length=254),
        ),
    ]
