# Generated by Django 3.0.3 on 2020-10-01 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201001_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
